// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElCarousel: typeof import("element-plus/es")["ElCarousel"]
  const ElCarouselItem: typeof import("element-plus/es")["ElCarouselItem"]
  const ElImage: typeof import("element-plus/es")["ElImage"]
  const ElScrollbar: typeof import("element-plus/es")["ElScrollbar"]
}
export {}
