// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    ElCarousel: typeof import("element-plus/es")["ElCarousel"]
    ElCarouselItem: typeof import("element-plus/es")["ElCarouselItem"]
    ElImage: typeof import("element-plus/es")["ElImage"]
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"]
    MenuList: typeof import("./src/components/layout/menu/menu-list.vue")["default"]
    MsBanner: typeof import("./src/components/common/ms-banner.vue")["default"]
    MsCoverPlay: typeof import("./src/components/common/ms-cover-play.vue")["default"]
    MsTitle: typeof import("./src/components/common/ms-title.vue")["default"]
    MusicMenu: typeof import("./src/components/layout/menu/music-menu.vue")["default"]
  }
}

export {}
